spring.application.name=staff-time-management
spring.datasource.url=jdbc:postgresql://localhost:5432/staff-time-management
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
server.port=8086
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver